### ISSUE TITLE
adamgoose/sentry migrate - nothing to migrate

### ISSUE THREAD

**Issue by christill** [adamgoose/saasframe#1]
When I run

php artisan migrate --package=adamgoose/sentry

It doesnt affect the database and returns:

Nothing to migrate.

**Comment by adamgoose** [comment]
Typo in the instructions! My bad.

```
php artisan migrate --package=adamgoose/saasframe
```

https://github.com/adamgoose/saasframe/commit/3f3eac782898274fa99b56e34b09f33e692bf893

**Comment by christill** [comment]
Oh yeah. I've sorted anyway. I did it manually.

Thanks!
