### ISSUE TITLE
adamgoose / saasframe not satisfiable by Laravel 4.1

### ISSUE THREAD

**Issue by rbk008** [adamgoose/saasframe#2]
I am working laravel 4.1, And i am trying to add adamgoose / saasframe, I added the "adamgoose/saasframe": "dev-master" to the composer.json and if try to update the composer then it will show the error of not satisfiable, And adamgoose / saasframe only  satisfiable  by Laravel4.0. so any solution for this..?

**Comment by adamgoose** [comment]
@rbk008 Since you're not the only one asking the question, I thought I'd point you to #3.
