### ISSUE TITLE
Bump Illumiate\support version up for 4.1

### ISSUE THREAD

**Issue by ssx** [adamgoose/saasframe#3]
Hi @adamgoose,

Will there be any breaking changes for this running on 4.1? Haven't had chance to read through the code yet, but was aiming to use this for a project this weekend.

**Comment by adamgoose** [comment]
Thanks for the interest. I haven't worked with this in quite a while, but I'd be happy to go through it and make sure its compatible with 4.1. Stay tuned!

**Comment by BobRupholdt** [comment]
Anxiously awaiting!  Ok, maybe not "anxious" but I would like to see this working with 4.1.  For now, I'll setup a 4.0 and see how you've done it.  Perhaps I can work it out for 4.1 (but I'm not holding my breath)

**Comment by tshafer** [comment]
I am unsure if this will be worked on again as Taylor has released this.

https://github.com/laravel/cashier
